const PACKAGES_DEV_DEP: string[] = [
  '@types/chai',
  '@types/chai-as-promised',
  '@types/config',
  '@types/dotenv',
  '@types/express',
  '@types/faker',
  '@types/mocha',
  '@types/module-alias',
  '@types/node',
  '@types/pg',
  '@types/pino',
  '@types/sequelize',
  '@types/sinon',
  '@types/sinon-chai',
  '@types/supertest',
  'axios-mock-adapter',
  'chai',
  'chai-as-promised',
  'faker',
  'husky',
  'mocha',
  'module-alias',
  'nodemon',
  'npm-check',
  'nyc',
  'pino-pretty',
  'reflect-metadata',
  'sinon',
  'sinon-chai',
  'supertest',
  'ts-node',
  'tsconfig-paths',
  'tslint',
  'typescript',
];

export { PACKAGES_DEV_DEP };
