FROM node:{{ nodeVersion }}-alpine as builder
LABEL Name={{ appName }} Version=0.0.1
# Set environment variables
ENV APP_NAME {{ appName }}
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

RUN npm i -g npm

ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.1/dumb-init_1.2.1_amd64 /usr/local/bin/dumb-init

WORKDIR /$APP_NAME
COPY process.yml ./
COPY config config
COPY package*.json ./
RUN npm i
COPY ts*.json ./
COPY src src

RUN npm run build
COPY dist dist

FROM node:{{ nodeVersion }}-alpine as release
WORKDIR /{{ appName }}
COPY --from=builder /{{ appName }} ./
COPY --from=builder /usr/local/bin/dumb-init /usr/local/bin/dumb-init
EXPOSE 2222

RUN chmod +x /usr/local/bin/dumb-init
USER node
CMD ["dumb-init", "npm", "run", "start:prod"]
